### ISSUE TITLE
UnitTests runs not working for full regression

### ISSUE THREAD

**Issue by ellab123** [p-org/P#153] opened 2017-09-06 01:01 UTC
When running full regression test suite under P\Tst\RegressionTests on UnitTests, only first 50-100 tests run OK; after that, there's and error:
Message: System.AggregateException : One or more errors occurred.
  ----> System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.

This error usually occurs for the first failing test only; all tests afterwards also fail, but the errors could be different, most frequently "null prt exception".
If any of the failing tests are run again alone, they pass. 
So, the way I run full regression now is thru iterations: start with a full set, then run failing tests only, until they all pass.
It usually takes 3-4 iterations for the full regression.

**Comment by lovettchris** [comment] 2017-09-06 08:12
I wonder if there's a memory leak in the PCompilerService?  Check the memory usage of those processes and see if they steadily increase...

**Comment by ellab123** [comment] 2017-09-06 16:00
I can see that the memory usage in general does increase, so there must be a leak somewhere...
I will look at the separate processes specifically.

**Comment by ankushdesai** [comment] 2017-09-07 03:23
@ellab123 Just to confirm that the problem is in CompilerService, can you try to run unit tests using compiler (not pcompilerservice).

**Comment by ankushdesai** [comment] 2017-09-10 03:38
@ellab123 Can you try to reproduce the problem by disabling the parallelism.
I feel that the problem is with parallelism, My server machine has 64GB and hence am not able to reproduce the problem.

**Comment by ankushdesai** [comment] 2018-06-07 17:35
This has been fixed on the new compiler branch and compiler service is obsolete now.

**Closed by ankushdesai** 2018-06-07 17:35 UTC
