### ISSUE TITLE
Statecharts

### ISSUE THREAD

**Issue by maacl** [p-org/P#127] opened 2017-05-22 09:30 UTC
The language looks very interesting but for complex problems, managing a herd of state machines quickly becomes challenging, even with the useful visualizations. 

I would suggest you consider support for [statecharts](http://www.inf.ed.ac.uk/teaching/courses/seoc/2005_2006/resources/statecharts.pdf) which greatly assists in controlling the combinatorial explosion often resulting from the use of state machines, both on the level of code organisation and the visualization level.

**Comment by maacl** [comment] 2017-05-28 15:30
Why has this been marked wontfix? I would consider it an enhancement request at least worthy of consideration?

**Comment by maacl** [comment] 2017-07-11 21:07
Could you at least comment on why this is not feasible?

**Comment by shazqadeer** [comment] 2017-07-11 23:11
@maacl : Thanks for your interest.  StateCharts is definitely interesting for visualization but the current set of P developers don't have much experience or expertise with visualization.  That is the only reason why we have reduced the priority of visualization-related work items.  Do you have any suggestions for the kind of visualizations you might want?  Any interest in providing them for the general community?

**Comment by maacl** [comment] 2017-07-12 04:01
@shazqadeer Thanks for responding to this. I should clarify that visualisation is not the only reason I think statecharts could be of interest to the P language. Statecharts which introduces the concept of hierarchical statemachines is a great way of modelling many systems that become unwieldy using simple statemachines. For visulalisations to makes sense P would have to support such hierarchical statemachines. I am more than happy to provide some useful references if that would be of interest? 

Re the visulalisations I should mention that statecharts is part of the UML statndard from 2.2 and onwards, so any tool that suports the current UML standard also supports statecharts. There is also a nice free visulaiser for the W3C State Chart XML [SCXML](https://www.w3.org/TR/scxml/) standard, called [scxmlgui](https://github.com/fmorbini/scxmlgui).

If it is within my capabilities I would be happy to contribute.

**Comment by shazqadeer** [comment] 2017-07-12 18:36
P supports the "push" transition out of states which allows creation of a stack of states in the control of a state machine.  P also allows states to be grouped.  Together, these two features allow encoding hierarchical state machines by convention.  @ellab123 recently used these features to encode hierarchical state machines for a driver development team in Windows.  

@maacl :  Do you have some concrete applications that can benefit from visualization of hierarchical state machines?  Are you using P currently for any applications?

**Comment by maacl** [comment] 2017-07-12 19:01
@shazqadeer I am not currently using P but currently evaluating it. The specific application I have in mind is modeling of legal contracts, which would require visualisation to be feasible, both for informal verification but also for communication between the parties. Is there a publicly available example of a hierarchical state machine in P using the push and grouping features?

**Comment by shazqadeer** [comment] 2017-07-12 22:29
@ellab123 : Could you please respond to the question from maacl?

**Comment by cahartsell** [comment] 2017-08-21 17:15
I am also interested in hierarchical machines, particularly ones that support historical transitions as described in the Statecharts paper. Currently I am using two separate machines where the primary machine only sends events to the secondary machine when in one particular state, then waits for a response. This gives a pseudo-hierarchical machine, but is somewhat cumbersome especially since P does not seem to support shared variables.

Maybe an example of the push/group method described could clear things up, are there any examples available?

**Comment by shazqadeer** [comment] 2017-08-26 04:50
@cahartsell : Could you point us to the StateCharts paper that describes "historical transitions"?

**Comment by cahartsell** [comment] 2017-08-26 06:05
@shazqadeer The [statecharts](http://www.inf.ed.ac.uk/teaching/courses/seoc/2005_2006/resources/statecharts.pdf) paper maacl linked to previously discusses entering a state using history starting on page 8 (page 238 going by the printed page numbers). I don't see the words "historical transitions" verbatim though, sorry if that caused any confusion.

**Comment by ellab123** [comment] 2017-09-07 19:58
@cahartsell  
The RadioManager.p test shows how push/pop can be combined with groups to mimic hierarchical machines in P:
P\Tst\RegressionTests\Integration\Correct\RadioManager\RadioManager.p

In P, groups of states can be defined as follows:
group S {
	state S1 {}
	state S2 {}
}
States in the group S has to be referred to as S.S1, S.S2, including the references inside the group S.
If we want to mimic one machine (Caller) calling another machine (Callee), we could put all Callee's 
states into a group ("Callee" below), and then use "push" transition with the initial state of Callee:
group Callee {
	state Init {}
	state S {}
}
machine Caller {
...
	on E push Callee.Init;
...
}

The semantics of "push" transition is such that the Callee.Init state is pushed on top of the current 
state, thus creating a stack of states. After that, entry action of the Callee.Init state start 
executing."Return" from the Callee is implemented by using the "pop" statement.
This flow is demonstrated in the test RadioManager.p.
In the RadioManager.p test, the Caller machine's name Main, and the Callee's name is PrepareForStateChangeMachine, which is a group consisting of the two states: StopPreparation and StartPreparation.
In the state PreparingForStateChangeToOn of Main, there's a push transition:
on __unit push PrepareForStateChangeMachine.StartPreparation;
This transition pushes the state PrepareForStateChangeMachine.StartPreparation on top of the state 
PreparingForStateChangeToOn, while dequeueing the "__Unit" event.
In PrepareForStateChangeMachine.StartPreparation state, there's a "goto" transition to the 
PrepareForStateChangeMachine.StopPreparation state.
In this state, when dequeueing event Done, function _anon_StopPreparation_do_Done is called, which pops the stack, such that the state PreparingForStateChangeToOn of Main becomes the current state, thus "returning" from the callee.
Note that in this test, there is no "send" statement with "Done" event. It is assumed that one of the 
"model" functions declared in the program would do that. Model functions for this test are defined in a 
separate P file (omitted for this test).

**Comment by ankushdesai** [comment] 2020-11-04 03:35
@maacl Do you have any other question? Can we close this issue?

**Closed** 2020-11-04 03:35 UTC
Labels: Information
